Menambah Data Tanaman Pada Perhitungan Tanaman

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,74 +1,74 @@
-name: CI/CD Pipeline
+# name: CI/CD Pipeline
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-permissions:
-  contents: write
-  packages: write
+# permissions:
+#   contents: write
+#   packages: write
 
-jobs:
-  build_and_push:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+# jobs:
+#   build_and_push:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout Repository
+#         uses: actions/checkout@v4
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+#       - name: Set up QEMU
+#         uses: docker/setup-qemu-action@v2
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v2
 
-      - name: Log in to GHCR
-        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+#       - name: Log in to GHCR
+#         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-      - name: Build and Push Docker Image with Cache
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: ghcr.io/${{ github.repository_owner }}/spk-media-tanam-app:${{ vars.CURRENT_VERSION }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+#       - name: Build and Push Docker Image with Cache
+#         uses: docker/build-push-action@v4
+#         with:
+#           context: .
+#           push: true
+#           tags: ghcr.io/${{ github.repository_owner }}/spk-media-tanam-app:${{ vars.CURRENT_VERSION }}
+#           cache-from: type=gha
+#           cache-to: type=gha,mode=max
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build_and_push
-    steps:
-      - name: Setup SSH Key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H ${{ vars.HOST }} >> ~/.ssh/known_hosts
+#   deploy:
+#     runs-on: ubuntu-latest
+#     needs: build_and_push
+#     steps:
+#       - name: Setup SSH Key
+#         run: |
+#           mkdir -p ~/.ssh
+#           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
+#           chmod 600 ~/.ssh/id_rsa
+#           ssh-keyscan -H ${{ vars.HOST }} >> ~/.ssh/known_hosts
 
-      - name: Deploy via SSH
-        run: |
-          ssh -i ~/.ssh/id_rsa ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
-            set -e
-            cd ${{ vars.APP_PATH }}
+#       - name: Deploy via SSH
+#         run: |
+#           ssh -i ~/.ssh/id_rsa ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
+#             set -e
+#             cd ${{ vars.APP_PATH }}
 
-            echo "Logging in to GHCR..."
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || { echo "GHCR login failed"; exit 1; }
+#             echo "Logging in to GHCR..."
+#             echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || { echo "GHCR login failed"; exit 1; }
 
-            echo "Pulling new image..."
-            docker pull ghcr.io/${{ github.repository_owner }}/spk-media-tanam-app:${{ vars.CURRENT_VERSION }} || { echo "Docker pull failed"; exit 1; }
+#             echo "Pulling new image..."
+#             docker pull ghcr.io/${{ github.repository_owner }}/spk-media-tanam-app:${{ vars.CURRENT_VERSION }} || { echo "Docker pull failed"; exit 1; }
 
-            echo "Tagging image..."
-            docker tag ghcr.io/${{ github.repository_owner }}/spk-media-tanam-app:${{ vars.CURRENT_VERSION }} spk-media-tanam-app:${{ vars.CURRENT_VERSION }}
+#             echo "Tagging image..."
+#             docker tag ghcr.io/${{ github.repository_owner }}/spk-media-tanam-app:${{ vars.CURRENT_VERSION }} spk-media-tanam-app:${{ vars.CURRENT_VERSION }}
 
-            echo "Stopping existing containers..."
-            docker compose down || echo "No containers running, skipping shutdown."
+#             echo "Stopping existing containers..."
+#             docker compose down || echo "No containers running, skipping shutdown."
 
-            echo "Remove app-public volume..."
-            docker volume rm spk-media-tanamcodewithcyou_app-public || echo "Volume app-public tidak ditemukan, lanjut..."
+#             echo "Remove app-public volume..."
+#             docker volume rm spk-media-tanamcodewithcyou_app-public || echo "Volume app-public tidak ditemukan, lanjut..."
 
-            echo "Starting new containers..."
-            docker compose up -d || { echo "Docker compose up failed"; exit 1; }
+#             echo "Starting new containers..."
+#             docker compose up -d || { echo "Docker compose up failed"; exit 1; }
 
-            echo "Cleaning up unused images..."
-            docker image prune -f
-          EOF
+#             echo "Cleaning up unused images..."
+#             docker image prune -f
+#           EOF
